### ISSUE TITLE
ExtractUsnJrnl.exe Variable used without being declared

### ISSUE THREAD

**Issue by XenonofArcticus** [jschicht/ExtractUsnJrnl#1]
Command is:

ExtractUsnJrnl.exe C:
or 
Q:\Mawson>ExtractUsnJrnl64.exe C:\ Q:\Mawson\

Output is:
ExtractUsnJrnl v1.0.0.1

followed by a Windows dialog saying
Line 20772 (File "Q:\Mawson\ExtractUsnJrnl.exe"):
Error: Variable used without being declared.

Same error for 32-bit or 64-bit versions.

Windows 8.1/64, Administrative CMD shell. C: is an 880GB NTFS filesystem, Q: is a 16GB flash drive.

Other commands like
RawCopy64.exe C:0 Q:\Mawson\

worked fine.

**Comment by jschicht** [comment]
Fixed in version 1.0.0.2.
