### ISSUE TITLE
Unsupported 16-bit application

### ISSUE THREAD

**Issue by mrkuolematon** [jschicht/ExtractUsnJrnl#2]
![image](https://cloud.githubusercontent.com/assets/2911107/12917095/89d75ede-cf37-11e5-9445-76c50a7c82a8.png)
Getting this error when using the 64 bit version on a Windows 8.1 64bit machine.
Any solutions?

**Comment by jschicht** [comment]
Can you please verify:
- Which version you try?
- Where it was downloaded from?
- How it is executed (called from other program like cmd, double clicked, right-clicked etc )?
- If called from other program, which one and what bitness does it have (is it x64 or something else)?

**Comment by mrkuolematon** [comment]
Hey, just downloaded it again from this link: https://github.com/jschicht/ExtractUsnJrnl latest version, 1.0.0.2 I think. It is being called from a batch script, so in theory from command line.

**Comment by jschicht** [comment]
The simplest test would be to right-click the program and run as administrator. Choose correct drive to extract from and see if anything was dumped in current directory. If that succeeds there might be something wrong with the batch script (or the program that the batch is making a call to beforehand).

The program is tested and verified on Windows 8.1 x64.

**Comment by mrkuolematon** [comment]
![image](https://cloud.githubusercontent.com/assets/2911107/12947165/d4970448-cff9-11e5-9104-b388a00943a5.png)

When doing that it gives me this :/. Even more confusing since I open the program from that location, so yes, the program is in that folder path.

**Comment by jschicht** [comment]
Contact me directly at joakim.schicht@gmail.com and I am sure we can sort it out.

**Comment by jschicht** [comment]
Issue caused by client machine misconfiguration.
