### ISSUE TITLE
Variable used without being declared

### ISSUE THREAD

**Issue by mike-bailey** [jschicht/ExtractUsnJrnl#3]
Not sure if we're running the latest release or this is already fixed but I figured I'd report this.

Can provide more details as needed, since it's an active client I have to be selective.
Sorry about the limited information.

![image](https://cloud.githubusercontent.com/assets/7607089/26697108/c27ea31c-46c5-11e7-8eb4-336177806796.png)

**Comment by jschicht** [comment]
I would at a minimum know the exact version you are running as well as the exact commandline. If you have details you don't want to expose publicly you can email me at joakim.schicht@gmail.com

**Comment by mike-bailey** [comment]
I can get that at some point today, not sure when exactly. Got this filed as an issue while I am on vacation so my useful response time is slightly garbage.

**Comment by mike-bailey** [comment]
v1.0.0.1 from the looks of the changelog

ExtractUsnJrnl64.exe %SYSTEMDRIVE% %genericresultfoldervariable%

**Comment by jschicht** [comment]
Please try v1.0.0.4 and report back how that went.

**Comment by mike-bailey** [comment]
Unfortunately likely won't be able to since it's a client system we don't keep persistent access to but I'll put in a request.

**Comment by mike-bailey** [comment]
We encountered this again and had the chance to update, it resolved.
