### ISSUE TITLE
Caught by AV

### ISSUE THREAD

**Issue by marcurdy** [jschicht/ExtractUsnJrnl#4]
In the last month, ExtractUsnJrnl started getting quarantined by my AV. Now it is flagged as a standard Artemis. Do you have anything in your bag of tricks that can prevent it from looking malicious with Mcafee?

thanks.

**Comment by jschicht** [comment]
Do you know if it is specific to ExtractUsnJrnl or general to AutoIt compiled programs? Both the 32-bit and 64-bit version? Does your AV for instance complain about Mft2Csv or Indx2Csv?

**Comment by marcurdy** [comment]
Sorry for the delay. Only the 32-bit extractusnjrnl.exe is being flagged as Artemis!E931FCFD92EF. The other 32-bit and all 64-bit binaries pass through.

Mark

**Comment by marcurdy** [comment]
Any thoughts here? I currently disable AV temporarily in order to have this on my system.

**Comment by jschicht** [comment]
Maybe you can run a test and see if this recompiled 32-bit 
[ExtractUsnJrnl.zip](https://github.com/jschicht/ExtractUsnJrnl/files/1334851/ExtractUsnJrnl.zip)
version goes through.

**Comment by marcurdy** [comment]
That fixed it. Someone likely marked the last hash as malicious. Thanks.
