### ISSUE TITLE
Crashes on Windows 2008 R2

### ISSUE THREAD

**Issue by 0xpaulbenoit** [jschicht/ExtractUsnJrnl#5]
<img width="294" alt="screen shot 2018-06-25 at 12 09 44 pm" src="https://user-images.githubusercontent.com/17418941/41862167-20ac6f5e-7871-11e8-960d-ed156d0edddf.png">

**Comment by jschicht** [comment]
Please test the latest version.

**Comment by 0xpaulbenoit** [comment]
It works now on 2008 R2. Thank you.
